# Generated by Django 3.2.20 on 2024-03-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination_Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('age', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominate_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q6', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q7', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q8', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q9', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q10', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q12', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q13', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q14', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q15', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q16', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q17', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q18', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q19', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q20', models.TextField(blank=True, default='', null=True)),
                ('q21', models.TextField(blank=True, default='', null=True)),
                ('q22', models.TextField(blank=True, default='', null=True)),
                ('q23', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
    ]
