# Generated by Django 3.2.20 on 2024-03-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination_form',
            name='q1_others',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='nomination_form',
            name='q7_others',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
