# Generated by Django 3.2.20 on 2024-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20240304_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination_form',
            name='q11',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
